### ISSUE TITLE
pyemma.msm.io.read_dtraj behaves unexpectedly when file contains floats

### ISSUE THREAD

**Issue by marscher** [markovmodel/msmtools#15]
_From @fabian-paul on July 13, 2015 14:28_

``` Python
import numpy as np
import pyemma

np.savetxt('disctraj', [1.0,2,3])
pyemma.msm.io.read_dtraj('disctraj') # array([1])
```

I think the correct behavior would be to raise an exception of to cast to int.

_Copied from original issue: markovmodel/PyEMMA#414_

**Comment by marscher** [comment]
thanks for reporting, this issue belongs now to msmtools repo

**Comment by marscher** [comment]
read_dtraj uses dtype=int, so it might get confused by floating point input data. That was never intended to use, but it should be more robust. Reading as float and casting down to float might be an option.

**Comment by trendelkampschroer** [comment]
The function read_dtraj uses numpy.fromstring to make reading ascii-dtrajs as fast as possible. Unfortunately np.fromstring does not check whether the requested data-type is the type specified in the file. 

I posted an numpy issue about this,

https://github.com/numpy/numpy/issues/6076

The current implementation of read_dtraj is very fast compared to np.loadtxt and I wouldn't like to sacrifice the large speed gain by using something safer and much slower. 

Maybe there is a fast and safe solution, but I can't think of it from the top of my head right now. 

Let me know if you have any suggestions.

**Comment by marscher** [comment]
The speedup is most probable due to not type checking every element. The question is, what we want to have: 1. robustness or 2. speed.

**Comment by franknoe** [comment]
Can't we catch that problem and sort it out afterwards?

Am 14/07/15 um 20:38 schrieb Martin K. Scherer:

> The speedup is most probable due to not type checking every element. 
> The question is, what we want to have: 1. robustness or 2. speed.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/issues/15#issuecomment-121336559.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
then we would need to write our own parser, since numpy does not give us an exception and an incomplete "array" of values red so far.

**Comment by franknoe** [comment]
No, don't do that. Can we read a small chunk of the data and decide 
based on that if everything worked?

Am 14/07/15 um 20:46 schrieb Martin K. Scherer:

> then we would need to write our own parser, since numpy does not give 
> us an exception and an incomplete "array" of values red so far.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/issues/15#issuecomment-121338267.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Like the coordinates.data.py_csv_reader? :+1:

**Comment by marscher** [comment]
we just need to add error checking there.

**Comment by marscher** [comment]
For super large files it may the only way reading such a file actually will work. So the speedup from using a (in my opinion) incomplete reader genfromtxt is neglect-able.

**Comment by fabian-paul** [comment]
While the numpy folks fix this, why can't we cast explicitly?

``` Python
lines='1.0\n2.0\n3.0\n'
np.fromstring(lines, dtype=float, sep="\n").astype(int) # array([1, 2, 3])
```

By the way, np.fromstring doesn't raise any exception, even for nonsense data

``` Python
np.fromstring('ärrör', dtype=float, sep=' ')) # array([-1.])
```

**Comment by trendelkampschroer** [comment]
@fabian-paul: This seems to be an easy fix. I think it depends on what we want to encourage/support in the usage. 

a) Force the user to ensure that a dtraj is really a one column file of ints
b) Support everything that can be casted to a 1-dim array of ints

I would rather raise an Error if the user supplies dtrajs in the wrong format, so that he can have a look at his input and decide if something is wrong or he just needs to save it in the right format (which will safe a bit of disk space and ensure that the data can be identified from the file content, ie. a one column file of ints).

In any case we would need some checks ensuring that the user doesn't supply data in the wrong format, but at the same time this should be done as fast as possible, because we will potentially be reading lots of different dtrajs files so that the checks we do might slow things down considerably.

**Comment by fabian-paul** [comment]
I also favor raising an exception. It's just that numpy is outstandingly stupid in the handling of integers.
Saving an array of ints with np.savetxt generates a file with floats! Then when you try to read that in again with np.fromstring, you get only the first element. How dumb is that!
I think the numpy developers have to fix these two things before we rely on these functions. I hope that this will be fixed soon. I think in the meantime we could live with a quick fix and don't put a lot of effort in finding workarounds for the numpy bugs.

**Comment by trendelkampschroer** [comment]
I wouldn't say it as strong as that: 

http://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html

it clearly has to do with convention for the fmt keyword in numpy.savetxt. I think it is easy to overlook that np.savetxt requires you to specify an integer format if you want ints in the file, since the default format is scientific with 18 digits precision. I don't think the numpy developers will change that behavior since from the signature of savetxt it was never desired to infer the output format from the dtype. 

By the way, it is also problematic to save complex numbers to ascii files using savetxt.

If you want to enforce dtype consistency in io-operations you have to use the binary *.npy format or you have to carefully specify fmt when using savetxt. 

By the way you can also use msmtools.dtraj.write_dtraj on an array of ints. It will ensure that data is saved in the right format.

**Comment by marscher** [comment]
fixed upstream
